### ISSUE TITLE
Docker Compose for Orthanc Dockers

### ISSUE THREAD

**Issue by powersaudrey25** [uiowaSEP2024/002_ImagePro#101]
**If this feature request related to a problem? Please describe.**

We have dockers for an internal PACS and a hospital PACS and they currently run on independent networks. Implementing Docker compose will allow them to work together.

**Alternatives Considered If Applicable**

None
**Rationale**

Eventually we want to dockerize all components of our application and we will need to use docker compose.

**Implementation Ideas**

**Additional Context**

**Comment by Ivan-E-Johnson** [comment]
After discussion this will not be completing this
