### ISSUE TITLE
Remove API Key generation from Provider

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [uiowaSEP2024/002_ImagePro#149]
# Summary
Only developers need access to the api keys so we shouldn't have that functionality for the providers or customers. Also API keys need to be set BEFORE running the agent.

**Comment by powersaudrey25** [comment]
Implementation process:

- hospital users do not have this functionality this will not change
- remove 'generate api key' option from provider frontend
- run test suite (should see failing tests) and refactor

- seed the database with api keys 
- set an api key in env.local and env.test
- pull that value from those files in the receiver agent

Admins will have api key generation functionality but this in not in the scope of this issue and will be covered in #152
