### ISSUE TITLE
Merge precommit files

### ISSUE THREAD

**Issue by zmorris248** [uiowaSEP2024/002_ImagePro#28]
## Description

As a developer, <br>
So that I can have an integrated repository for development, <br>
I want one merged precommit.yaml file for the repository

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _All relevant pieces from each precommit file are put into the root precommit file_
- [x] _All other non root precommit files are deleted_

**Comment by powersaudrey25** [comment]
kept our pre-commit and deleted theirs
