### ISSUE TITLE
Hospital Viewing Studies in Progress

### ISSUE THREAD

**Issue by mbrzus** [uiowaSEP2024/002_ImagePro#32]
## Description
_Use the following format to name and describe your user stories_

As a "hospital", <br>
So that "I can see the study progress", <br>
I want "to be able to see all running/scheduled studies"

_Example:_
_As a customer,_
_so that I can see my past purchases,_
_I want to view my billing history_

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _Criteria/Task 1 User (hospital) can see studies in progress on UI
- [x] _Criteria/Task 2 Logs are correctly used to propagate DB and UI

**Comment by powersaudrey25** [comment]
@mbrzus will you fill out the project info? unsure of scope

**Comment by mbrzus** [comment]
We can currently log in, run mock jobs and see the study progress with all steps. This is visible as both Customer and Provider
