### ISSUE TITLE
Reorganize Code Base

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [uiowaSEP2024/002_ImagePro#40]
### Problem Description

Integrating a different team's repository has introduced redundant files like duplicate `requirements.txt`, multiple `.gitignore` files, etc., which complicates the project structure and version control.

### Alternatives Considered

- **Manual Review:** Inefficient and prone to missing duplicates.
- **Scripted Cleanup:** Scripts can automate removal but might require frequent updates.
- **Merge Tools:** Tools like `git merge` can help but may not catch all types of redundancy.

### Rationale

Streamlining the repository by removing duplicates and unnecessary files will enhance development efficiency, simplify file navigation, and ensure a clean, organized codebase that aligns with our project's extension goals.

### Implementation Suggestions

- **Consolidate Files:** Merge similar files (e.g., `requirements.txt`, `.gitignore`) and remove duplicates.
- **Automation Tool:** Develop or use existing tools for detecting and removing redundant files.
- **Documentation Update:** Update docs to reflect the new, streamlined structure and any changes in file handling practices.
- **Peer Review:** Incorporate code reviews to catch issues automation might miss.

### Additional Context

This cleanup is part of a broader effort to integrate and extend the functionality of an acquired codebase, making it crucial to maintain or improve code quality during the process.

**Comment by saurabh-lohiya** [comment]
Can I work on this issue?
