### ISSUE TITLE
Sonar Duplicate Code

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [uiowaSEP2024/002_ImagePro#46]
Here's how to format your issue using Markdown for better readability and organization on platforms like GitHub or GitLab:

---

### Title
**Eliminate Duplicate Code Detected by SonarCloud**

### Describe the bug
SonarCloud analysis identified duplicate code across the codebase, affecting maintainability.

### Steps to Identify
Duplicate code was detected in SonarCloud's analysis, not through user interaction.

### Expected behavior
Code should adhere to DRY principles with minimal duplicate blocks.

### Actual Behavior
Several components have duplicate code, increasing technical debt.

### Environment
- **OS:** [e.g., Windows]
- **Project Version:** [e.g., 1.2.3]
- **SonarCloud Version:** [Specify if known]

### Additional context
Detected in:
- **Component 1:** `path/to/duplicate`
- **Component 2:** `another/path/to/duplicate`

### Possible Fix
1. Review and abstract duplicate code into common methods.
2. Ensure code changes are covered by tests.
3. Verify fixes with a SonarCloud re-scan.

**Comment by mbrzus** [comment]
Duplicates decreased and Sonarcloud checks pass.
