### ISSUE TITLE
ER Diagram of old job-mon-app

### ISSUE THREAD

**Issue by zmorris248** [uiowaSEP2024/002_ImagePro#48]
## Description
_Use the following format to name and describe your user stories_

As a developer, <br>
So that visualize the current state of the job-monitoring-app schema, <br>
I want ER diagrams of their database

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [x] _All models are included in the diagram with their attributes_
- [x] _Relationships are shown in the diagram_
- [x] _Diagram is posted in a place that is accessible to the team_

**Comment by powersaudrey25** [comment]
Looking at the backend/models directory I see the following tables:

- api keys
- events
- jobs
- job configs
- metadata configs
- step configs
- users

**Comment by powersaudrey25** [comment]
The diagram is in our shared SEP folder in onedrive, also 

![job-mon-app-original drawio (1)](https://github.com/uiowaSEP2024/002_ImagePro/assets/57544141/816d2b99-1b59-4fe6-9db9-f08a4e93df5f)

**Comment by zmorris248** [comment]
Diagram has been uploaded to the sharefile.
