### ISSUE TITLE
Additional DICOM data

### ISSUE THREAD

**Issue by zmorris248** [uiowaSEP2024/002_ImagePro#76]
## Description
As a developer,
so that I can have more comprehensive testing of my product,
I want more example DICOM data available to me to test

## Acceptance Criteria
_What are some implicit tasks/criteria to be achieved within this story?_
- [ ] _DICOM study data is available to test with our system, as many studies as possible_

**Comment by powersaudrey25** [comment]
Here are possible datasets that might work with our example tool: 
@Ivan-E-Johnson @mbrzus let us know if these would work, if not we will keep looking

- https://central.xnat.org/app/template/XDATScreen_report_xnat_projectData.vm/search_element/xnat:projectData/search_field/xnat:projectData.ID/search_value/CENTRAL_OASIS_CS

- https://www.cancerimagingarchive.net/collection/upenn-gbm/
- https://www.cancerimagingarchive.net/collection/gbm-dsc-mri-dro/

- https://www.nitrc.org/ir/app/action/DisplayItemAction/search_element/xnat%3AprojectData/search_field/xnat%3AprojectData.ID/search_value/dlbs

- https://www.nitrc.org/ir/app/template/XDATScreen_report_xnat_projectData.vm/search_element/xnat:projectData/search_field/xnat:projectData.ID/search_value/cs_schizbull08
- https://www.nitrc.org/ir/app/template/XDATScreen_report_xnat_projectData.vm/search_element/xnat:projectData/search_field/xnat:projectData.ID/search_value/parktdi
- https://www.nitrc.org/ir/app/template/XDATScreen_report_xnat_projectData.vm/search_element/xnat:projectData/search_field/xnat:projectData.ID/search_value/ixi
