### ISSUE TITLE
Static Code Analysis Tool - Sonar

### ISSUE THREAD

**Issue by Ivan-E-Johnson** [uiowaSEP2024/002_ImagePro#9]
**If this feature request related to a problem? Please describe.**

Yes, this feature is related to the problem that Professor Johnson is requiring us to utilize a static code analysis tool. 

**Rationale**

Implementing this early will allow us to create quality code that adheres to a standard style.

**Implementation Ideas**

Sonarqube

**Additional Context**

Research on how to use is needed, should also be able integrate into a workflow

**Comment by powersaudrey25** [comment]
I can go ahead an look more into using/setting up Sonar, pretty sure there's a gh action for it as well

**Comment by powersaudrey25** [comment]
SonarCloud has been configured as a GitHub app in our repo.
No need for a workflow, when a PR is created or commits are pushed to an existing one SonarCloud will run a quality gate scan and it will appear as a comment. You can view details of the run when you click the link.

As a future task, analyzing code coverage has not been setup, could look into that
